=== lindsaygelle/AWSAnimalCrossing/src/api_gateway/model/clothing_accessory/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "maxProperties": 17,
    "minProperties": 17,
    "properties": {
        "buy_currency": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string",
                "null"
            ]
        },
        "buy_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 2400,
            "minimum": 80,
            "type": [
                "null",
                "integer"
            ]
        },
        "color_1": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "color_2": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "exchange_currency": {
            "maxLength": 10,
            "minLength": 4,
            "type": [
                "string",
                "null"
            ]
        },
        "exchange_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 1600,
            "minimum": 400,
            "type": [
                "null",
                "integer"
            ]
        },
        "hha_points": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 573,
            "minimum": 51,
            "type": [
                "integer"
            ]
        },
        "internal_id": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 14850,
            "minimum": 148,
            "type": [
                "integer"
            ]
        },
        "is_craftable": {
            "type": [
                "boolean"
            ]
        },
        "is_equipment": {
            "type": [
                "boolean"
            ]
        },
        "is_unlocked": {
            "type": [
                "boolean"
            ]
        },
        "name": {
            "maxLength": 24,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "sell_currency": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string"
            ]
        },
        "sell_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 2500,
            "minimum": 10,
            "type": [
                "integer"
            ]
        },
        "style_1": {
            "maxLength": 8,
            "minLength": 4,
            "type": [
                "string"
            ]
        },
        "style_2": {
            "maxLength": 8,
            "minLength": 4,
            "type": [
                "string"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "buy_currency",
        "buy_price",
        "color_1",
        "color_2",
        "exchange_currency",
        "exchange_price",
        "hha_points",
        "internal_id",
        "is_craftable",
        "is_equipment",
        "is_unlocked",
        "name",
        "sell_currency",
        "sell_price",
        "style_1",
        "style_2",
        "unique_entry_id"
    ],
    "title": "ClothingAccessory",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/raw/clothing_other.json
[
    {
        "buy_currency": "Bells",
        "buy_price": 3000,
        "color_1": "Black",
        "color_2": "White",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 51,
        "internal_id": 13103,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "horizontal-striped wet suit",
        "sell_currency": "Bells",
        "sell_price": 750,
        "style_1": "Active",
        "style_2": "Active",
        "unique_entry_id": "6L2xDvYdeFstLHY86"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 3000,
        "color_1": "Red",
        "color_2": "White",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 51,
        "internal_id": 12986,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "horizontal-striped wet suit",
        "sell_currency": "Bells",
        "sell_price": 750,
        "style_1": "Active",
        "style_2": "Active",
        "unique_entry_id": "3TDPbxuAzdDjSSHyA"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 3000,
        "color_1": "Yellow",
        "color_2": "White",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 51,
        "internal_id": 13102,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "horizontal-striped wet suit",
        "sell_currency": "Bells",
        "sell_price": 750,
        "style_1": "Active",
        "style_2": "Active",
        "unique_entry_id": "ngqeKA7GqE55ezKww"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 3000,
        "color_1": "Blue",
        "color_2": "White",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 51,
        "internal_id": 13101,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "horizontal-striped wet suit",
        "sell_currency": "Bells",
        "sell_price": 750,
        "style_1": "Active",
        "style_2": "Active",
        "unique_entry_id": "hSJxcwRHv7qnKp93f"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 3000,
        "color_1": "Yellow",
        "color_2": "Black",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 51,
        "internal_id": 13099,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "leaf-print wet suit",
        "sell_currency": "Bells",
        "sell_price": 750,
        "style_1": "Active",
        "style_2": "Gorgeous",
        "unique_entry_id": "dzprxbw5CzvxNWHt7"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 3000,
        "color_1": "Green",
        "color_2": "Black",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 51,
        "internal_id": 13100,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "leaf-print wet suit",
        "sell_currency": "Bells",
        "sell_price": 750,
        "style_1": "Active",
        "style_2": "Gorgeous",
        "unique_entry_id": "3qhdPQngftbrtWgHM"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 3000,
        "color_1": "Aqua",
        "color_2": "Black",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 51,
        "internal_id": 12981,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "leaf-print wet suit",
        "sell_currency": "Bells",
        "sell_price": 750,
        "style_1": "Active",
        "style_2": "Gorgeous",
        "unique_entry_id": "mCuc5u3XpnyQqcR8G"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 3000,
        "color_1": "Purple",
        "color_2": "Black",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 51,
        "internal_id": 13098,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "leaf-print wet suit",
        "sell_currency": "Bells",
        "sell_price": 750,
        "style_1": "Active",
        "style_2": "Gorgeous",
        "unique_entry_id": "GZwvXzEMwCfhuNTHe"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Black",
        "color_2": "Green",
        "exchange_currency": "Nook Miles",
        "exchange_price": 800,
        "hha_points": 151,
        "internal_id": 12970,
        "is_craftable": false,
        "is_equipment": false,
        "is_unlocked": true,
        "name": "Nook Inc. wet suit",
        "sell_currency": "Bells",
        "sell_price": 4000,
        "style_1": "Active",
        "style_2": "Simple",
        "unique_entry_id": "jjwdLhmb3X42fvtHa"
    }
]
