=== lindsaygelle/AWSAnimalCrossing/src/api_gateway/model/furniture_artwork/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "maxProperties": 11,
    "minProperties": 11,
    "properties": {
        "buy_currency": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string"
            ]
        },
        "buy_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 4980,
            "minimum": 4980,
            "type": [
                "integer"
            ]
        },
        "color_1": {
            "maxLength": 6,
            "minLength": 4,
            "type": [
                "string"
            ]
        },
        "color_2": {
            "maxLength": 6,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "hha_points": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 451,
            "minimum": 17,
            "type": [
                "integer"
            ]
        },
        "internal_id": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 12629,
            "minimum": 2,
            "type": [
                "integer"
            ]
        },
        "is_unlocked": {
            "type": [
                "boolean"
            ]
        },
        "name": {
            "maxLength": 24,
            "minLength": 12,
            "type": [
                "string"
            ]
        },
        "sell_currency": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string",
                "null"
            ]
        },
        "sell_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 1245,
            "minimum": 1245,
            "type": [
                "null",
                "integer"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "buy_currency",
        "buy_price",
        "color_1",
        "color_2",
        "hha_points",
        "internal_id",
        "is_unlocked",
        "name",
        "sell_currency",
        "sell_price",
        "unique_entry_id"
    ],
    "title": "FurnitureArtwork",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/raw/furniture_artwork.json
[
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Beige",
        "color_2": "Beige",
        "hha_points": 451,
        "internal_id": 12619,
        "is_unlocked": true,
        "name": "academic painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "xfTf9sfyLkxHQEz4u"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Beige",
        "color_2": "Beige",
        "hha_points": 17,
        "internal_id": 12620,
        "is_unlocked": true,
        "name": "academic painting",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "5KNFAo3LkdTTJPQkd"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Black",
        "hha_points": 451,
        "internal_id": 56,
        "is_unlocked": true,
        "name": "amazing painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "Sg6MCSG3m9tvjGWoj"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Black",
        "hha_points": 17,
        "internal_id": 55,
        "is_unlocked": true,
        "name": "amazing painting",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "vc2Ebu4Pkn443zYiN"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Gray",
        "color_2": "Gray",
        "hha_points": 451,
        "internal_id": 1337,
        "is_unlocked": true,
        "name": "ancient statue",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "zpAsguge9Yb29ksjS"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Gray",
        "color_2": "Gray",
        "hha_points": 17,
        "internal_id": 1338,
        "is_unlocked": true,
        "name": "ancient statue",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "fXbsrcXirg6miBoqT"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Blue",
        "hha_points": 451,
        "internal_id": 14,
        "is_unlocked": true,
        "name": "basic painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "Xhn8ZjtbdZeET3NXR"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Blue",
        "hha_points": 17,
        "internal_id": 13,
        "is_unlocked": true,
        "name": "basic painting",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "o4px7Mx9g2Zk6NHvC"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "White",
        "color_2": "White",
        "hha_points": 451,
        "internal_id": 1341,
        "is_unlocked": true,
        "name": "beautiful statue",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "iscap6FsmDZdNP5dw"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "White",
        "color_2": "White",
        "hha_points": 17,
        "internal_id": 1342,
        "is_unlocked": true,
        "name": "beautiful statue",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "w9vrMbhJNj6JHkznu"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Green",
        "color_2": "Gray",
        "hha_points": 451,
        "internal_id": 78,
        "is_unlocked": true,
        "name": "calm painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "7QgYY7KuhauCnS37H"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Beige",
        "color_2": "White",
        "hha_points": 451,
        "internal_id": 44,
        "is_unlocked": true,
        "name": "common painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "GE6sppzKjqkG7sRoz"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Yellow",
        "color_2": "Green",
        "hha_points": 451,
        "internal_id": 12622,
        "is_unlocked": true,
        "name": "detailed painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "T2QA6mqARHfToTJpQ"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Yellow",
        "color_2": "Green",
        "hha_points": 17,
        "internal_id": 12623,
        "is_unlocked": true,
        "name": "detailed painting",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "m9TkAsJFFkpQ9Hr4s"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Beige",
        "color_2": "Beige",
        "hha_points": 451,
        "internal_id": 38,
        "is_unlocked": true,
        "name": "dynamic painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "BMBiEvuooPCwpzHj7"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Green",
        "color_2": "Green",
        "hha_points": 451,
        "internal_id": 12541,
        "is_unlocked": true,
        "name": "familiar statue",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "e45RimLWaxcoBYLNq"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Beige",
        "hha_points": 451,
        "internal_id": 18,
        "is_unlocked": true,
        "name": "famous painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "23b6Mtp42pbXaLiGj"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Beige",
        "hha_points": 17,
        "internal_id": 17,
        "is_unlocked": true,
        "name": "famous painting",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "ppnz4rtJf2L6FK6YN"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Yellow",
        "color_2": "Brown",
        "hha_points": 451,
        "internal_id": 50,
        "is_unlocked": true,
        "name": "flowery painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "aDZWPQ79YhLCMRqAE"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "White",
        "color_2": "White",
        "hha_points": 451,
        "internal_id": 1333,
        "is_unlocked": true,
        "name": "gallant statue",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "hNbaWeaJCdihGnHM9"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "White",
        "color_2": "White",
        "hha_points": 17,
        "internal_id": 1334,
        "is_unlocked": true,
        "name": "gallant statue",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "aoJwhWz4TTkNHrgg4"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Blue",
        "color_2": "Gray",
        "hha_points": 451,
        "internal_id": 12624,
        "is_unlocked": true,
        "name": "glowing painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "89wbjB4u9oKjrKiZB"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Yellow",
        "color_2": "Red",
        "hha_points": 451,
        "internal_id": 6,
        "is_unlocked": true,
        "name": "graceful painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "8M8N84TgtyATYSaPK"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Yellow",
        "color_2": "Red",
        "hha_points": 17,
        "internal_id": 5,
        "is_unlocked": true,
        "name": "graceful painting",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "PJCq2YjGNkP3rLYAs"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Yellow",
        "hha_points": 451,
        "internal_id": 1339,
        "is_unlocked": true,
        "name": "great statue",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "AAE89LXrdnv7yxs7p"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Black",
        "hha_points": 451,
        "internal_id": 12535,
        "is_unlocked": true,
        "name": "informative statue",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "QW7tW8LLK5ReWvNeT"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Blue",
        "color_2": "Blue",
        "hha_points": 17,
        "internal_id": 12536,
        "is_unlocked": true,
        "name": "informative statue",
        "sell_currency": null,
        "sell_price": null,
        "unique_entry_id": "qsBfFStS8mFJWotF3"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 4980,
        "color_1": "Black",
        "color_2": "Yellow",
        "hha_points": 451,
        "internal_id": 42,
        "is_unlocked": true,
        "name": "jolly painting",
        "sell_currency": "Bells",
        "sell_price": 1245,
        "unique_entry_id": "JmuDLy5Gzy5L98TYi"
    },
    {
