=== lindsaygelle/AWSAnimalCrossing/api_gateway/model/clothing_dress_up/model.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "buy_price": {
            "maxLength": 7000,
            "minLength": 450,
            "type": [
                "null",
                "number"
            ]
        },
        "clothing_group_id": {
            "maxLength": 4,
            "minLength": 1,
            "type": [
                "string"
            ]
        },
        "color_1": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "color_2": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "exchange_currency": {
            "maxLength": 14,
            "minLength": 10,
            "type": [
                "null",
                "string"
            ]
        },
        "exchange_price": {
            "maxLength": 900,
            "minLength": 20,
            "type": [
                "null",
                "number"
            ]
        },
        "filename": {
            "maxLength": 38,
            "minLength": 22,
            "type": [
                "string"
            ]
        },
        "gender": {
            "maxLength": 7,
            "minLength": 4,
            "type": [
                "string"
            ]
        },
        "hha_points": {
            "maxLength": 573,
            "minLength": 0,
            "type": [
                "number"
            ]
        },
        "image_closet": {
            "type": [
                "null"
            ]
        },
        "image_storage": {
            "type": [
                "null"
            ]
        },
        "internal_id": {
            "maxLength": 14986,
            "minLength": 127,
            "type": [
                "number"
            ]
        },
        "is_crafted": {
            "type": [
                "boolean"
            ]
        },
        "is_equipment": {
            "type": [
                "boolean"
            ]
        },
        "is_unlocked": {
            "type": [
                "boolean"
            ]
        },
        "name": {
            "maxLength": 29,
            "minLength": 4,
            "type": [
                "string"
            ]
        },
        "sell_price": {
            "maxLength": 80000,
            "minLength": 10,
            "type": [
                "null",
                "number"
            ]
        },
        "style_1": {
            "maxLength": 8,
            "minLength": 4,
            "type": [
                "string"
            ]
        },
        "style_2": {
            "maxLength": 8,
            "minLength": 4,
            "type": [
                "string"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        },
        "variant_name": {
            "maxLength": 16,
            "minLength": 3,
            "type": [
                "null",
                "string"
            ]
        },
        "version_added": {
            "maxLength": 6,
            "minLength": 5,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "style_2",
        "name",
        "style_1",
        "version_added",
        "hha_points",
        "gender",
        "is_equipment",
        "color_1",
        "filename",
        "clothing_group_id",
        "unique_entry_id",
        "color_2",
        "is_unlocked",
        "image_closet",
        "image_storage",
        "is_crafted",
        "internal_id"
    ],
    "title": "ClothingDressUp",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/clothing_other.json
[{"name": "horizontal-striped wet suit", "image_closet": null, "image_storage": null, "variant_name": "Black", "is_crafted": false, "buy_price": 3000, "sell_price": 750, "hha_points": 51, "color_1": "Black", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "style_1": "Active", "style_2": "Active", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalNGreco3", "clothing_group_id": "1260", "internal_id": 13103, "unique_entry_id": "6L2xDvYdeFstLHY86"}, {"name": "horizontal-striped wet suit", "image_closet": null, "image_storage": null, "variant_name": "Red", "is_crafted": false, "buy_price": 3000, "sell_price": 750, "hha_points": 51, "color_1": "Red", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "style_1": "Active", "style_2": "Active", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalNGreco0", "clothing_group_id": "1260", "internal_id": 12986, "unique_entry_id": "3TDPbxuAzdDjSSHyA"}, {"name": "horizontal-striped wet suit", "image_closet": null, "image_storage": null, "variant_name": "Yellow", "is_crafted": false, "buy_price": 3000, "sell_price": 750, "hha_points": 51, "color_1": "Yellow", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "style_1": "Active", "style_2": "Active", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalNGreco2", "clothing_group_id": "1260", "internal_id": 13102, "unique_entry_id": "ngqeKA7GqE55ezKww"}, {"name": "horizontal-striped wet suit", "image_closet": null, "image_storage": null, "variant_name": "Blue", "is_crafted": false, "buy_price": 3000, "sell_price": 750, "hha_points": 51, "color_1": "Blue", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "style_1": "Active", "style_2": "Active", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalNGreco1", "clothing_group_id": "1260", "internal_id": 13101, "unique_entry_id": "hSJxcwRHv7qnKp93f"}, {"name": "leaf-print wet suit", "image_closet": null, "image_storage": null, "variant_name": "Yellow", "is_crafted": false, "buy_price": 3000, "sell_price": 750, "hha_points": 51, "color_1": "Yellow", "color_2": "Black", "exchange_price": null, "exchange_currency": null, "gender": "Free", "style_1": "Active", "style_2": "Gorgeous", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalLRashguard2", "clothing_group_id": "1259", "internal_id": 13099, "unique_entry_id": "dzprxbw5CzvxNWHt7"}, {"name": "leaf-print wet suit", "image_closet": null, "image_storage": null, "variant_name": "Green", "is_crafted": false, "buy_price": 3000, "sell_price": 750, "hha_points": 51, "color_1": "Green", "color_2": "Black", "exchange_price": null, "exchange_currency": null, "gender": "Free", "style_1": "Active", "style_2": "Gorgeous", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalLRashguard3", "clothing_group_id": "1259", "internal_id": 13100, "unique_entry_id": "3qhdPQngftbrtWgHM"}, {"name": "leaf-print wet suit", "image_closet": null, "image_storage": null, "variant_name": "Light blue", "is_crafted": false, "buy_price": 3000, "sell_price": 750, "hha_points": 51, "color_1": "Aqua", "color_2": "Black", "exchange_price": null, "exchange_currency": null, "gender": "Free", "style_1": "Active", "style_2": "Gorgeous", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalLRashguard0", "clothing_group_id": "1259", "internal_id": 12981, "unique_entry_id": "mCuc5u3XpnyQqcR8G"}, {"name": "leaf-print wet suit", "image_closet": null, "image_storage": null, "variant_name": "Purple", "is_crafted": false, "buy_price": 3000, "sell_price": 750, "hha_points": 51, "color_1": "Purple", "color_2": "Black", "exchange_price": null, "exchange_currency": null, "gender": "Free", "style_1": "Active", "style_2": "Gorgeous", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalLRashguard1", "clothing_group_id": "1259", "internal_id": 13098, "unique_entry_id": "GZwvXzEMwCfhuNTHe"}, {"name": "Nook Inc. wet suit", "image_closet": null, "image_storage": null, "variant_name": null, "is_crafted": false, "buy_price": null, "sell_price": 4000, "hha_points": 151, "color_1": "Black", "color_2": "Green", "exchange_price": 800, "exchange_currency": "Nook Miles", "gender": "Free", "style_1": "Active", "style_2": "Simple", "is_equipment": false, "version_added": "1.3.0", "is_unlocked": true, "filename": "TopsTexMarinesuitNormalLNook0", "clothing_group_id": "1258", "internal_id": 12970, "unique_entry_id": "jjwdLhmb3X42fvtHa"}]
