=== lindsaygelle/AWSAnimalCrossing/src/api_gateway/model/furniture_rug/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "maxProperties": 14,
    "minProperties": 14,
    "properties": {
        "buy_currency": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string",
                "null"
            ]
        },
        "buy_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 2000,
            "minimum": 1000,
            "type": [
                "null",
                "integer"
            ]
        },
        "color_1": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "color_2": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "exchange_currency": {
            "maxLength": 14,
            "minLength": 4,
            "type": [
                "string",
                "null"
            ]
        },
        "exchange_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 1800,
            "minimum": 4,
            "type": [
                "null",
                "integer"
            ]
        },
        "hha_points": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 501,
            "minimum": 89,
            "type": [
                "integer"
            ]
        },
        "internal_id": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 14707,
            "minimum": 7322,
            "type": [
                "integer"
            ]
        },
        "is_craftable": {
            "type": [
                "boolean"
            ]
        },
        "is_unlocked": {
            "type": [
                "boolean"
            ]
        },
        "name": {
            "maxLength": 27,
            "minLength": 8,
            "type": [
                "string"
            ]
        },
        "sell_currency": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string"
            ]
        },
        "sell_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 10360,
            "minimum": 88,
            "type": [
                "integer"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "buy_currency",
        "buy_price",
        "color_1",
        "color_2",
        "exchange_currency",
        "exchange_price",
        "hha_points",
        "internal_id",
        "is_craftable",
        "is_unlocked",
        "name",
        "sell_currency",
        "sell_price",
        "unique_entry_id"
    ],
    "title": "FurnitureRug",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/raw/furniture_rug.json
[
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Brown",
        "color_2": "Beige",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 201,
        "internal_id": 12335,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "acorn rug",
        "sell_currency": "Bells",
        "sell_price": 2400,
        "unique_entry_id": "Y2BtGdBHjHDAZ5aMi"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1500,
        "color_1": "Gray",
        "color_2": "Gray",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 137,
        "internal_id": 7356,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "aluminum rug",
        "sell_currency": "Bells",
        "sell_price": 375,
        "unique_entry_id": "vFkuGbx8Sh2MDLEsq"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Red",
        "color_2": "Red",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 7327,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "apple rug",
        "sell_currency": "Bells",
        "sell_price": 1200,
        "unique_entry_id": "5GsjYsaz9NDtQ6QFB"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Yellow",
        "color_2": "Yellow",
        "exchange_currency": "Nook Miles",
        "exchange_price": 1200,
        "hha_points": 151,
        "internal_id": 12214,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "Bell-bag rug",
        "sell_currency": "Bells",
        "sell_price": 6000,
        "unique_entry_id": "KfRapmYKpizqQWzCg"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1500,
        "color_1": "Black",
        "color_2": "Gray",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 137,
        "internal_id": 11104,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "black blocks rug",
        "sell_currency": "Bells",
        "sell_price": 375,
        "unique_entry_id": "4kj8FXzMTqvZvqEra"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1500,
        "color_1": "Black",
        "color_2": "Black",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 137,
        "internal_id": 7382,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "black wooden-deck rug",
        "sell_currency": "Bells",
        "sell_price": 375,
        "unique_entry_id": "kQDKkEGfdAjqPxd4w"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1000,
        "color_1": "Black",
        "color_2": "Orange",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 89,
        "internal_id": 7594,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "black-design kitchen mat",
        "sell_currency": "Bells",
        "sell_price": 250,
        "unique_entry_id": "G7CAPiAEpYv6QKbsL"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 2000,
        "color_1": "Blue",
        "color_2": "Green",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 253,
        "internal_id": 8467,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue argyle rug",
        "sell_currency": "Bells",
        "sell_price": 500,
        "unique_entry_id": "uw8DvCwwBia7ozA72"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1500,
        "color_1": "Blue",
        "color_2": "Blue",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 137,
        "internal_id": 11102,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue blocks rug",
        "sell_currency": "Bells",
        "sell_price": 375,
        "unique_entry_id": "Mjxd8kenDFZgTFXcm"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 2000,
        "color_1": "Blue",
        "color_2": "Blue",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 253,
        "internal_id": 7467,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue dotted rug",
        "sell_currency": "Bells",
        "sell_price": 500,
        "unique_entry_id": "JAAx9zSMrjXKKw2ij"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1500,
        "color_1": "Blue",
        "color_2": "Blue",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 137,
        "internal_id": 12387,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue exercise mat",
        "sell_currency": "Bells",
        "sell_price": 375,
        "unique_entry_id": "DdiGJyEREa2QAMXRM"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 2000,
        "color_1": "Aqua",
        "color_2": "White",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 253,
        "internal_id": 12391,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue Hawaiian quilt rug",
        "sell_currency": "Bells",
        "sell_price": 500,
        "unique_entry_id": "L3nBtt43WwHPYTpDE"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 2000,
        "color_1": "Blue",
        "color_2": "Black",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 253,
        "internal_id": 9316,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue kilim-style carpet",
        "sell_currency": "Bells",
        "sell_price": 500,
        "unique_entry_id": "MhvdxvmyKtddid2G2"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1000,
        "color_1": "Blue",
        "color_2": "Blue",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 89,
        "internal_id": 8394,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue kitchen mat",
        "sell_currency": "Bells",
        "sell_price": 250,
        "unique_entry_id": "SLBDbK365pHRnKE5k"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1500,
        "color_1": "Blue",
        "color_2": "Blue",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 137,
        "internal_id": 9546,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue medium round mat",
        "sell_currency": "Bells",
        "sell_price": 375,
        "unique_entry_id": "JfLKCbWRz4CozZYpH"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1000,
        "color_1": "Blue",
        "color_2": "Blue",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 89,
        "internal_id": 9310,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue message mat",
        "sell_currency": "Bells",
        "sell_price": 250,
        "unique_entry_id": "5grLuDzGkNL4DYk4r"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 2000,
        "color_1": "Blue",
        "color_2": "Beige",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 253,
        "internal_id": 8035,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue Persian rug",
        "sell_currency": "Bells",
        "sell_price": 500,
        "unique_entry_id": "CDY97qjWg4xG6egyS"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 2000,
        "color_1": "Blue",
        "color_2": "Blue",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 253,
        "internal_id": 9564,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue shaggy rug",
        "sell_currency": "Bells",
        "sell_price": 500,
        "unique_entry_id": "v4ZJPY2ToZPHXp6KH"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1000,
        "color_1": "Blue",
        "color_2": "Blue",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 89,
        "internal_id": 9549,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue small round mat",
        "sell_currency": "Bells",
        "sell_price": 250,
        "unique_entry_id": "BxaqCsC7TqwGdHpib"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 2000,
        "color_1": "Blue",
        "color_2": "White",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 253,
        "internal_id": 7533,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue stripes rug",
        "sell_currency": "Bells",
        "sell_price": 500,
        "unique_entry_id": "dAHzKeTqwA9wD2yfa"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 1500,
        "color_1": "Blue",
        "color_2": "Colorful",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 137,
        "internal_id": 7404,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue vinyl sheet",
        "sell_currency": "Bells",
        "sell_price": 375,
        "unique_entry_id": "b8xZjiyqLPWJsgt73"
    },
    {
        "buy_currency": "Bells",
        "buy_price": 2000,
        "color_1": "Blue",
        "color_2": "Aqua",
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 253,
        "internal_id": 7458,
        "is_craftable": false,
        "is_unlocked": true,
        "name": "blue wavy rug",
        "sell_currency": "Bells",
        "sell_price": 500,
