=== lindsaygelle/AWSAnimalCrossing/src/api_gateway/model/furniture_interior_structure/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "maxProperties": 16,
    "minProperties": 16,
    "properties": {
        "buy_currency": {
            "type": [
                "null"
            ]
        },
        "buy_price": {
            "type": [
                "null"
            ]
        },
        "color_1": {
            "maxLength": 6,
            "minLength": 3,
            "type": [
                "string",
                "null"
            ]
        },
        "color_2": {
            "maxLength": 6,
            "minLength": 3,
            "type": [
                "string",
                "null"
            ]
        },
        "cyrus_customize_currency": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string",
                "null"
            ]
        },
        "cyrus_customize_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 3100,
            "minimum": 1000,
            "type": [
                "null",
                "integer"
            ]
        },
        "exchange_currency": {
            "type": [
                "null"
            ]
        },
        "exchange_price": {
            "type": [
                "null"
            ]
        },
        "hha_points": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 103,
            "minimum": 103,
            "type": [
                "integer"
            ]
        },
        "internal_id": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 14602,
            "minimum": 12681,
            "type": [
                "integer"
            ]
        },
        "is_craftable": {
            "type": [
                "boolean"
            ]
        },
        "is_unlocked": {
            "type": [
                "boolean"
            ]
        },
        "name": {
            "maxLength": 28,
            "minLength": 12,
            "type": [
                "string"
            ]
        },
        "sell_currency": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string"
            ]
        },
        "sell_price": {
            "exclusiveMaximum": false,
            "exclusiveMinimum": false,
            "maximum": 80000,
            "minimum": 700,
            "type": [
                "integer"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "buy_currency",
        "buy_price",
        "color_1",
        "color_2",
        "cyrus_customize_currency",
        "cyrus_customize_price",
        "exchange_currency",
        "exchange_price",
        "hha_points",
        "internal_id",
        "is_craftable",
        "is_unlocked",
        "name",
        "sell_currency",
        "sell_price",
        "unique_entry_id"
    ],
    "title": "FurnitureInteriorStructure",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/raw/furniture_interior_structure.json
[
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Red",
        "color_2": "Brown",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14596,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "brick pillar",
        "sell_currency": "Bells",
        "sell_price": 800,
        "unique_entry_id": "vKhroLoma4RWAqc38"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "White",
        "color_2": "Beige",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14596,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "brick pillar",
        "sell_currency": "Bells",
        "sell_price": 800,
        "unique_entry_id": "6ntCK44tpEZ76T77a"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Gray",
        "color_2": "Gray",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14596,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "brick pillar",
        "sell_currency": "Bells",
        "sell_price": 800,
        "unique_entry_id": "8MCJkAqEindE3FP2C"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Gray",
        "color_2": "Gray",
        "cyrus_customize_currency": null,
        "cyrus_customize_price": null,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14602,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "concrete pillar",
        "sell_currency": "Bells",
        "sell_price": 1200,
        "unique_entry_id": "Scz7WHrn8zJqdESLF"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Yellow",
        "color_2": "Yellow",
        "cyrus_customize_currency": null,
        "cyrus_customize_price": null,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14600,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "golden pillar",
        "sell_currency": "Bells",
        "sell_price": 40000,
        "unique_entry_id": "97Zm9hRj3BQDLQM3H"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Red",
        "color_2": "Brown",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 13901,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low brick island counter",
        "sell_currency": "Bells",
        "sell_price": 800,
        "unique_entry_id": "ZAA4zjnJGQDpPnNpe"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "White",
        "color_2": "Brown",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 13901,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low brick island counter",
        "sell_currency": "Bells",
        "sell_price": 800,
        "unique_entry_id": "uaziCiTaLxWgvx3p3"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Gray",
        "color_2": "Brown",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 13901,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low brick island counter",
        "sell_currency": "Bells",
        "sell_price": 800,
        "unique_entry_id": "ek3qyESiioFjp8Tv9"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Gray",
        "color_2": "Gray",
        "cyrus_customize_currency": null,
        "cyrus_customize_price": null,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 13898,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low concrete island counter",
        "sell_currency": "Bells",
        "sell_price": 1200,
        "unique_entry_id": "xt8pEhjXJrR4gKWeY"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Yellow",
        "color_2": "Yellow",
        "cyrus_customize_currency": null,
        "cyrus_customize_price": null,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14333,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low golden island counter",
        "sell_currency": "Bells",
        "sell_price": 40000,
        "unique_entry_id": "6sKWwLgkQRj23WFP7"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Gray",
        "color_2": "Gray",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14337,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low marble island counter",
        "sell_currency": "Bells",
        "sell_price": 1200,
        "unique_entry_id": "6Z5cNgANBAyaLuRWe"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "White",
        "color_2": "White",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14337,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low marble island counter",
        "sell_currency": "Bells",
        "sell_price": 1200,
        "unique_entry_id": "rLYobhs2h4PpW4KjE"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Black",
        "color_2": "Black",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1700,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14337,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low marble island counter",
        "sell_currency": "Bells",
        "sell_price": 1200,
        "unique_entry_id": "nF2aG9ZmfoTAE9Nkh"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "White",
        "color_2": "White",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1000,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14308,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low simple island counter",
        "sell_currency": "Bells",
        "sell_price": 700,
        "unique_entry_id": "hNyMCjtHztETRswEJ"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Pink",
        "color_2": "Pink",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1000,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14308,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low simple island counter",
        "sell_currency": "Bells",
        "sell_price": 700,
        "unique_entry_id": "bFFmaC4vxcv8u8hBT"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Aqua",
        "color_2": "Aqua",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1000,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14308,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low simple island counter",
        "sell_currency": "Bells",
        "sell_price": 700,
        "unique_entry_id": "6GYofpcAybQqX5GYk"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Yellow",
        "color_2": "Yellow",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1000,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14308,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low simple island counter",
        "sell_currency": "Bells",
        "sell_price": 700,
        "unique_entry_id": "zJDcAcDvRPpzA3u6d"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Red",
        "color_2": "Red",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1000,
        "exchange_currency": null,
        "exchange_price": null,
        "hha_points": 103,
        "internal_id": 14308,
        "is_craftable": true,
        "is_unlocked": true,
        "name": "low simple island counter",
        "sell_currency": "Bells",
        "sell_price": 700,
        "unique_entry_id": "QpK8Ldtypv39FSt5n"
    },
    {
        "buy_currency": null,
        "buy_price": null,
        "color_1": "Blue",
        "color_2": "Blue",
        "cyrus_customize_currency": "Bells",
        "cyrus_customize_price": 1000,
        "exchange_currency": null,
