=== lindsaygelle/AWSAnimalCrossing/src/api_gateway/model/clothing_umbrella/model.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "buy_price": {
            "maxLength": 1670,
            "minLength": 650,
            "type": [
                "null",
                "number"
            ]
        },
        "color_1": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "color_2": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "exchange_currency": {
            "maxLength": 10,
            "minLength": 4,
            "type": [
                "null",
                "string"
            ]
        },
        "exchange_price": {
            "maxLength": 1800,
            "minLength": 700,
            "type": [
                "null",
                "number"
            ]
        },
        "filename": {
            "maxLength": 22,
            "minLength": 12,
            "type": [
                "string"
            ]
        },
        "gender": {
            "maxLength": 4,
            "minLength": 4,
            "type": [
                "string"
            ]
        },
        "hha_points": {
            "maxLength": 501,
            "minLength": 3,
            "type": [
                "number"
            ]
        },
        "image_storage": {
            "type": [
                "null"
            ]
        },
        "internal_id": {
            "maxLength": 14464,
            "minLength": 5861,
            "type": [
                "number"
            ]
        },
        "is_crafted": {
            "type": [
                "boolean"
            ]
        },
        "is_equipment": {
            "type": [
                "boolean"
            ]
        },
        "is_unlocked": {
            "type": [
                "boolean"
            ]
        },
        "name": {
            "maxLength": 26,
            "minLength": 12,
            "type": [
                "string"
            ]
        },
        "sell_price": {
            "maxLength": 3500,
            "minLength": 80,
            "type": [
                "number"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        },
        "version_added": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "color_1",
        "color_2",
        "filename",
        "gender",
        "hha_points",
        "image_storage",
        "internal_id",
        "is_crafted",
        "is_equipment",
        "is_unlocked",
        "name",
        "sell_price",
        "unique_entry_id",
        "version_added"
    ],
    "title": "ClothingUmbrella",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/clothing_umbrella.json
[{"name": "apple umbrella", "image_storage": null, "is_crafted": true, "buy_price": null, "sell_price": 1400, "hha_points": 103, "color_1": "Yellow", "color_2": "Red", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaApple0", "internal_id": 9948, "unique_entry_id": "FPxdw28z9s2gYgjmr"}, {"name": "bat umbrella", "image_storage": null, "is_crafted": false, "buy_price": 840, "sell_price": 210, "hha_points": 3, "color_1": "Black", "color_2": "Black", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaBat0", "internal_id": 6919, "unique_entry_id": "EZnRx49foq3M36yQ4"}, {"name": "beach umbrella", "image_storage": null, "is_crafted": false, "buy_price": 770, "sell_price": 192, "hha_points": 3, "color_1": "Blue", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaBeach0", "internal_id": 9957, "unique_entry_id": "3SSFuv6LiH63jych3"}, {"name": "bear umbrella", "image_storage": null, "is_crafted": false, "buy_price": 1570, "sell_price": 392, "hha_points": 3, "color_1": "Brown", "color_2": "Beige", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaBear0", "internal_id": 7167, "unique_entry_id": "s7KoPpysn27AeC5zi"}, {"name": "black chic umbrella", "image_storage": null, "is_crafted": false, "buy_price": 1620, "sell_price": 405, "hha_points": 3, "color_1": "Black", "color_2": "Black", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaPacodarace5", "internal_id": 12137, "unique_entry_id": "p8yg9xiFwPscNDJNg"}, {"name": "black lace umbrella", "image_storage": null, "is_crafted": false, "buy_price": 750, "sell_price": 187, "hha_points": 3, "color_1": "Black", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaRace0", "internal_id": 6915, "unique_entry_id": "7vuSb5AutpNQA573q"}, {"name": "blue dot parasol", "image_storage": null, "is_crafted": false, "buy_price": 750, "sell_price": 187, "hha_points": 3, "color_1": "Blue", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaPolkadot2", "internal_id": 9956, "unique_entry_id": "SwKuBi2vT7K365A3p"}, {"name": "blue shiny-bows parasol", "image_storage": null, "is_crafted": false, "buy_price": 1620, "sell_price": 405, "hha_points": 3, "color_1": "Blue", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaPacodarace2", "internal_id": 12134, "unique_entry_id": "BxZ4XdtfJEyWyBPFe"}, {"name": "blue umbrella", "image_storage": null, "is_crafted": false, "buy_price": 770, "sell_price": 192, "hha_points": 3, "color_1": "Blue", "color_2": "Blue", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaStandard2", "internal_id": 9959, "unique_entry_id": "XyJaqSLnBjh5J6vLp"}, {"name": "busted umbrella", "image_storage": null, "is_crafted": false, "buy_price": 1570, "sell_price": 392, "hha_points": 3, "color_1": "Black", "color_2": "Black", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaBroken0", "internal_id": 7182, "unique_entry_id": "gkHD9GKJT9eAekxWQ"}, {"name": "camo umbrella", "image_storage": null, "is_crafted": false, "buy_price": 650, "sell_price": 162, "hha_points": 3, "color_1": "Green", "color_2": "Beige", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaOutdoor0", "internal_id": 6923, "unique_entry_id": "RJYB5itM7mDdtWHpv"}, {"name": "candy umbrella", "image_storage": null, "is_crafted": false, "buy_price": 770, "sell_price": 192, "hha_points": 3, "color_1": "Pink", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaGingham0", "internal_id": 6926, "unique_entry_id": "F6KFg5Yhzgf78pudR"}, {"name": "cherry umbrella", "image_storage": null, "is_crafted": true, "buy_price": null, "sell_price": 1400, "hha_points": 103, "color_1": "Red", "color_2": "Red", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaCherry0", "internal_id": 9949, "unique_entry_id": "YwHY3LQXsDeM2iosy"}, {"name": "cherry-blossom umbrella", "image_storage": null, "is_crafted": true, "buy_price": null, "sell_price": 2800, "hha_points": 201, "color_1": "Pink", "color_2": "Green", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaCherryblossom0", "internal_id": 9945, "unique_entry_id": "vTu5kLPipRb69vJA3"}, {"name": "DAL umbrella", "image_storage": null, "is_crafted": false, "buy_price": null, "sell_price": 1010, "hha_points": 251, "color_1": "Blue", "color_2": "Blue", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaDoc0", "internal_id": 9560, "unique_entry_id": "vTdEjywjFjr8AkePD"}, {"name": "eggy parasol", "image_storage": null, "is_crafted": false, "buy_price": 750, "sell_price": 187, "hha_points": 3, "color_1": "Yellow", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaPolkadot1", "internal_id": 9955, "unique_entry_id": "qf7Hn5CKMDMBpge9r"}, {"name": "exquisite parasol", "image_storage": null, "is_crafted": false, "buy_price": 1670, "sell_price": 417, "hha_points": 3, "color_1": "Yellow", "color_2": "Pink", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaChina0", "internal_id": 7171, "unique_entry_id": "tFFuizXunsrHcMbEj"}, {"name": "fairy-tale umbrella", "image_storage": null, "is_crafted": false, "buy_price": 820, "sell_price": 205, "hha_points": 3, "color_1": "Green", "color_2": "Yellow", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaFairytale0", "internal_id": 7175, "unique_entry_id": "xKBGNFJd2qpWeDWjo"}, {"name": "fish umbrella", "image_storage": null, "is_crafted": false, "buy_price": null, "sell_price": 80, "hha_points": 501, "color_1": "Blue", "color_2": "Aqua", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaFish0", "internal_id": 8768, "unique_entry_id": "bvwaqJav8wmjPj2RC"}, {"name": "frog umbrella", "image_storage": null, "is_crafted": false, "buy_price": 1570, "sell_price": 392, "hha_points": 3, "color_1": "Green", "color_2": "Green", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaFrog0", "internal_id": 6925, "unique_entry_id": "nDBiFvLtf5KeStQNv"}, {"name": "gelato umbrella", "image_storage": null, "is_crafted": false, "buy_price": 750, "sell_price": 187, "hha_points": 3, "color_1": "Colorful", "color_2": "Colorful", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaTricolor0", "internal_id": 7180, "unique_entry_id": "tupHZa6zDdFvobTEt"}, {"name": "ghost umbrella", "image_storage": null, "is_crafted": false, "buy_price": 1670, "sell_price": 417, "hha_points": 3, "color_1": "White", "color_2": "White", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaTeruteru0", "internal_id": 6924, "unique_entry_id": "83zEbSL3S3dty4YjN"}, {"name": "grape umbrella", "image_storage": null, "is_crafted": false, "buy_price": 1550, "sell_price": 387, "hha_points": 3, "color_1": "Purple", "color_2": "Green", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaGrape0", "internal_id": 6911, "unique_entry_id": "TJ9cw4XSj64u3uEsx"}, {"name": "green chic umbrella", "image_storage": null, "is_crafted": false, "buy_price": 1620, "sell_price": 405, "hha_points": 3, "color_1": "Green", "color_2": "Black", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaPacodarace4", "internal_id": 12136, "unique_entry_id": "u2YWae8oz23XcT4u9"}, {"name": "green umbrella", "image_storage": null, "is_crafted": false, "buy_price": 770, "sell_price": 192, "hha_points": 3, "color_1": "Green", "color_2": "Green", "exchange_price": null, "exchange_currency": null, "gender": "Free", "is_equipment": true, "version_added": "1.0.0", "is_unlocked": true, "filename": "UmbrellaStandard3", "internal_id": 9960, "unique_entry_id": "8Hf4oRy3cQdundDJK"}, {"name": "hydrangea umbrel
