=== lindsaygelle/AWSAnimalCrossing/api_gateway/model/furniture_poster/model.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "buy_price": {
            "maxLength": 1000,
            "minLength": 1000,
            "type": [
                "number"
            ]
        },
        "color_1": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "color_2": {
            "maxLength": 8,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "filename": {
            "maxLength": 19,
            "minLength": 14,
            "type": [
                "string"
            ]
        },
        "hha_points": {
            "maxLength": 251,
            "minLength": 251,
            "type": [
                "number"
            ]
        },
        "image": {
            "type": [
                "null"
            ]
        },
        "internal_id": {
            "maxLength": 14869,
            "minLength": 10312,
            "type": [
                "number"
            ]
        },
        "is_unlocked": {
            "type": [
                "boolean"
            ]
        },
        "name": {
            "maxLength": 22,
            "minLength": 11,
            "type": [
                "string"
            ]
        },
        "sell_price": {
            "maxLength": 250,
            "minLength": 250,
            "type": [
                "number"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        },
        "version_added": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "name",
        "image",
        "hha_points",
        "version_added",
        "color_1",
        "sell_price",
        "filename",
        "unique_entry_id",
        "color_2",
        "buy_price",
        "is_unlocked",
        "internal_id"
    ],
    "title": "FurniturePoster",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/furniture_poster.json
[{"name": "Ace's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Blue", "color_2": "Red", "version_added": "2.0.0", "is_unlocked": true, "filename": "PosterNpcNmlBrd09", "internal_id": 13044, "unique_entry_id": "6dbxo8yShZQk36uXj"}, {"name": "Admiral's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Green", "color_2": "Blue", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlBrd06", "internal_id": 10814, "unique_entry_id": "3LW8HyqLZTJRaGQT9"}, {"name": "Agent S's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Blue", "color_2": "Gray", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlSqu05", "internal_id": 10425, "unique_entry_id": "bZu92nbNfGmQvp54D"}, {"name": "Agnes's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Pink", "color_2": "Black", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlPig17", "internal_id": 10401, "unique_entry_id": "2wZBfe8Ed7QMvQ8tX"}, {"name": "Al's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Red", "color_2": "Aqua", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlGor08", "internal_id": 10590, "unique_entry_id": "sat2PG8L97DymZbQw"}, {"name": "Alfonso's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Orange", "color_2": "Red", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlCrd00", "internal_id": 10382, "unique_entry_id": "NjW35Zc7MnTipYZbg"}, {"name": "Alice's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Beige", "color_2": "White", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlKal01", "internal_id": 10411, "unique_entry_id": "M89MiTg6MwBt38bYC"}, {"name": "Alli's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Aqua", "color_2": "Red", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlCrd01", "internal_id": 10655, "unique_entry_id": "6yDr388PQngpmfKyw"}, {"name": "Amelia's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Red", "color_2": "White", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlPbr01", "internal_id": 10687, "unique_entry_id": "xDPzyfpuH42GzRP25"}, {"name": "Anabelle's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Yellow", "color_2": "Blue", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlAnt03", "internal_id": 10800, "unique_entry_id": "BpX27retKhbmi8f3F"}, {"name": "Anchovy's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Brown", "color_2": "Aqua", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlBrd02", "internal_id": 10782, "unique_entry_id": "fNnTbreeuJ9AxCA6M"}, {"name": "Angus's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Red", "color_2": "Orange", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlBul00", "internal_id": 10807, "unique_entry_id": "wGwxFH8nwYXuDj8Mv"}, {"name": "Anicotti's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Green", "color_2": "Brown", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlMus10", "internal_id": 10413, "unique_entry_id": "YFQoYdCCWf74rHXxX"}, {"name": "Ankha's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Yellow", "color_2": "Brown", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlCat19", "internal_id": 10416, "unique_entry_id": "YNxQgR8caq9EAvm8b"}, {"name": "Annalisa's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Beige", "color_2": "Pink", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlAnt08", "internal_id": 10824, "unique_entry_id": "QLhdJiM4EPJBdZvZD"}, {"name": "Annalise's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Brown", "color_2": "Purple", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlHrs09", "internal_id": 10573, "unique_entry_id": "KeP7vMfGPMihtEeRN"}, {"name": "Antonio's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Blue", "color_2": "Yellow", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlAnt01", "internal_id": 10795, "unique_entry_id": "TeuSXPWPNyvqpWyF7"}, {"name": "Apollo's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Black", "color_2": "White", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlPbr00", "internal_id": 10512, "unique_entry_id": "SiD2CXoom2ufiKaHY"}, {"name": "Apple's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Red", "color_2": "Yellow", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlHam01", "internal_id": 10565, "unique_entry_id": "fqWJTtNBSXH4JTa4W"}, {"name": "Astrid's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "White", "color_2": "Black", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlKgr05", "internal_id": 10493, "unique_entry_id": "ha3PS72Re4aZznfPB"}, {"name": "Audie's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Red", "color_2": "Yellow", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlWol12", "internal_id": 10859, "unique_entry_id": "ji4EcitFLpu8pxguu"}, {"name": "Aurora's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Black", "color_2": "Red", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlPgn00", "internal_id": 10563, "unique_entry_id": "iPnQ3k2KAts6ZohZu"}, {"name": "Ava's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Beige", "color_2": "Pink", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlChn05", "internal_id": 10467, "unique_entry_id": "XuCCq3DgwaAREjgnY"}, {"name": "Avery's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Gray", "color_2": "Black", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlPbr05", "internal_id": 10370, "unique_entry_id": "5aP6GoQ2YiTHaN523"}, {"name": "Axel's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Blue", "color_2": "Red", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlElp06", "internal_id": 10319, "unique_entry_id": "5BGYmdDam5ddHkktX"}, {"name": "Azalea's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Pink", "color_2": "Aqua", "version_added": "2.0.0", "is_unlocked": true, "filename": "PosterNpcNmlRhn05", "internal_id": 13041, "unique_entry_id": "8wFw4jSNhERRikv7d"}, {"name": "Baabara's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Brown", "color_2": "Aqua", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlShp01", "internal_id": 10508, "unique_entry_id": "hmmcqfFiWWoWNQfre"}, {"name": "Bam's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Blue", "color_2": "Green", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlDer01", "internal_id": 10456, "unique_entry_id": "N5FWLxwNYM2Qb4CsD"}, {"name": "Bangle's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Brown", "color_2": "Green", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlTig03", "internal_id": 10672, "unique_entry_id": "waGuCcp47Jd8riQgL"}, {"name": "Barold's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Gray", "color_2": "Black", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlCbr16", "internal_id": 10583, "unique_entry_id": "F9dscB8bM2NRt4DHz"}, {"name": "Bea's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Aqua", "color_2": "Brown", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlDog10", "internal_id": 10632, "unique_entry_id": "QANup429jzLZ9RtGw"}, {"name": "Beardo's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Aqua", "color_2": "Brown", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlBea13", "internal_id": 10788, "unique_entry_id": "oDTLWzHGazre6rf2d"}, {"name": "Beau's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Aqua", "color_2": "Brown", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlDer07", "internal_id": 10396, "unique_entry_id": "akpHWn6ftgCh2DkQn"}, {"name": "Becky's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Purple", "color_2": "Red", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlChn09", "internal_id": 10580, "unique_entry_id": "FKSnKjqAcon3Xnsbh"}, {"name": "Bella's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Purple", "color_2": "White", "version_added": "1.0.0", "is_unlocked": true, "filename": "PosterNpcNmlMus02", "internal_id": 10681, "unique_entry_id": "2ZzkQFMSyPpDWBFwN"}, {"name": "Benedict's poster", "image": null, "buy_price": 1000, "sell_price": 250, "hha_points": 251, "color_1": "Red", "color_2": "Green", "vers
