=== lindsaygelle/AWSAnimalCrossing/api_gateway/model/construction/model.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "buy_price": {
            "maxLength": 228000,
            "minLength": 5000,
            "type": [
                "null",
                "number"
            ]
        },
        "category": {
            "maxLength": 7,
            "minLength": 4,
            "type": [
                "null",
                "string"
            ]
        },
        "filename": {
            "maxLength": 30,
            "minLength": 9,
            "type": [
                "string"
            ]
        },
        "image": {
            "type": [
                "null"
            ]
        },
        "name": {
            "maxLength": 26,
            "minLength": 8,
            "type": [
                "null",
                "string"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        },
        "version_added": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "filename",
        "version_added",
        "unique_entry_id",
        "image"
    ],
    "title": "Construction",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/construction.json
[{"name": "brick bridge", "image": null, "buy_price": 198000, "category": "Bridge", "filename": "BridgeBricks", "version_added": "1.0.0", "unique_entry_id": "Rvkrg9tcubTMakcBS"}, {"name": "iron bridge", "image": null, "buy_price": 228000, "category": "Bridge", "filename": "BridgeIron", "version_added": "1.0.0", "unique_entry_id": "RmQ6iiKkFf3Sy4iSQ"}, {"name": "log bridge", "image": null, "buy_price": 98000, "category": "Bridge", "filename": "BridgeLog", "version_added": "1.0.0", "unique_entry_id": "Px55sTfjKSbbMtjAK"}, {"name": "red zen bridge", "image": null, "buy_price": 228000, "category": "Bridge", "filename": "BridgeRed", "version_added": "1.0.0", "unique_entry_id": "jTziEHXkeYaugKDQQ"}, {"name": "stone bridge", "image": null, "buy_price": 168000, "category": "Bridge", "filename": "BridgeStone", "version_added": "1.0.0", "unique_entry_id": "JmrwC2tRRCCgbZnrp"}, {"name": "suspension bridge", "image": null, "buy_price": 129800, "category": "Bridge", "filename": "BridgeSuspension", "version_added": "1.0.0", "unique_entry_id": "q52JebMTHDqHJKBba"}, {"name": "wooden bridge", "image": null, "buy_price": 168000, "category": "Bridge", "filename": "BridgeWood", "version_added": "1.0.0", "unique_entry_id": "7oZ7FMrJEpBLZzsmw"}, {"name": "zen bridge", "image": null, "buy_price": 228000, "category": "Bridge", "filename": "BridgeJapanese", "version_added": "1.0.0", "unique_entry_id": "TbKbHzJM8j8ezmAEF"}, {"name": "basic door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorCercleWindowAR", "version_added": "1.0.0", "unique_entry_id": "HrAsZSpm2pRj2u8ad"}, {"name": "beige basic door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorCercleWindowGR", "version_added": "1.0.0", "unique_entry_id": "uF4YeCTGBx4Tawcp8"}, {"name": "beige simple door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorSimpleBR", "version_added": "1.0.0", "unique_entry_id": "jQFLgioHYBRbRkBYK"}, {"name": "beige windowed door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorWindowGR", "version_added": "1.0.0", "unique_entry_id": "oMqf22Pf8fZzeoJdY"}, {"name": "beige wooden door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorStandardGR", "version_added": "1.0.0", "unique_entry_id": "N5LASg9qjhgexBMe7"}, {"name": "black common door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorReliefHR", "version_added": "1.0.0", "unique_entry_id": "6mmdmWbK5ZRpbCsWc"}, {"name": "black fancy door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorCarvingBR", "version_added": "1.0.0", "unique_entry_id": "3ZahH8gvtHGdkEM68"}, {"name": "black imperial door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorChineseHR", "version_added": "1.0.0", "unique_entry_id": "qT9ghD7YkZpMDgBDf"}, {"name": "black latticework door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorLatticeHR", "version_added": "1.0.0", "unique_entry_id": "Kzu4WsZwmSWzLdMC6"}, {"name": "black rustic door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorSimplicityDR", "version_added": "1.0.0", "unique_entry_id": "TKDhdqyJBdrz8yQt6"}, {"name": "black vertical-panes door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorVerticalWindowHR", "version_added": "1.0.0", "unique_entry_id": "Z4efmoeAjzYLhTsKJ"}, {"name": "black zen door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorJapaneseER", "version_added": "1.0.0", "unique_entry_id": "AxrkW9SNKqmh9kX4S"}, {"name": "blue basic door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorCercleWindowER", "version_added": "1.0.0", "unique_entry_id": "BxqZmtEty82NDo8J3"}, {"name": "blue common door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorReliefCR", "version_added": "1.0.0", "unique_entry_id": "hfWfx4mxev3qjp2zH"}, {"name": "blue fancy door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorCarvingER", "version_added": "1.0.0", "unique_entry_id": "fm6MupiuPAK6HPNNj"}, {"name": "blue iron door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronCR", "version_added": "1.0.0", "unique_entry_id": "5tgy5p3AE38NBeG9B"}, {"name": "blue latticework door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorLatticeFR", "version_added": "1.0.0", "unique_entry_id": "JwdJLi5HHZe24DmkF"}, {"name": "blue metal-accent door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronpartsCR", "version_added": "1.0.0", "unique_entry_id": "YB3NZt9RRYJroWRcn"}, {"name": "blue rustic door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorSimplicityFR", "version_added": "1.0.0", "unique_entry_id": "8k4sCwWWqugmTYuw6"}, {"name": "blue simple door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorSimpleDR", "version_added": "1.0.0", "unique_entry_id": "cN2eTBiAPt2Bv8GTK"}, {"name": "blue vertical-panes door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorVerticalWindowDR", "version_added": "1.0.0", "unique_entry_id": "AJB8xQLjaJR2WrHBv"}, {"name": "blue windowed door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorWindowER", "version_added": "1.0.0", "unique_entry_id": "i5JLZk2vdr5jZ9nBC"}, {"name": "blue wooden door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorStandardER", "version_added": "1.0.0", "unique_entry_id": "okXxYSYZ8o2vceKQG"}, {"name": "brown imperial door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorChineseBR", "version_added": "1.0.0", "unique_entry_id": "SN5ik2H7HfGLuG9EN"}, {"name": "brown latticework door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorLatticeAR", "version_added": "1.0.0", "unique_entry_id": "a4Mft9ihDSpo4jusc"}, {"name": "brown metal-accent door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronpartsFR", "version_added": "1.0.0", "unique_entry_id": "8eztTyD69pNsq7Eee"}, {"name": "brown zen door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorJapaneseCR", "version_added": "1.0.0", "unique_entry_id": "3bWWrFPG7N5NcAKbS"}, {"name": "burgundy basic door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorCercleWindowDR", "version_added": "1.0.0", "unique_entry_id": "vuSF9u2vtgf95NREh"}, {"name": "common door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorReliefAR", "version_added": "1.0.0", "unique_entry_id": "8Gx8LKMb7ipbF9qKa"}, {"name": "cyan vertical-panes door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorVerticalWindowJR", "version_added": "1.0.0", "unique_entry_id": "CTyPWnQDRGqMcDEyf"}, {"name": "dark-brown iron grill door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronGrillGR", "version_added": "1.0.0", "unique_entry_id": "CQFAjS99WqxTu4QDJ"}, {"name": "deep-green simple door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorSimpleGR", "version_added": "1.0.0", "unique_entry_id": "Gyibc6G9u5Zv4fMdJ"}, {"name": "gray common door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorReliefFR", "version_added": "1.0.0", "unique_entry_id": "mEBW6Y6gLFpBpibwA"}, {"name": "gray iron door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronGR", "version_added": "1.0.0", "unique_entry_id": "27cPAfi2DYBEzzgto"}, {"name": "gray iron grill door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronGrillHR", "version_added": "1.0.0", "unique_entry_id": "uzLEvMD46GzBZQ3mN"}, {"name": "gray latticework door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorLatticeER", "version_added": "1.0.0", "unique_entry_id": "ZCfMjY9ED5jW87aZY"}, {"name": "gray simple door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorSimpleCR", "version_added": "1.0.0", "unique_entry_id": "QjS2nzSqHCLCcLGKQ"}, {"name": "gray windowed door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorWindowFR", "version_added": "1.0.0", "unique_entry_id": "Y7W4HKFy49BLvabBD"}, {"name": "gray wooden door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorStandardFR", "version_added": "1.0.0", "unique_entry_id": "C2LhRZFynjh6x5gQB"}, {"name": "green basic door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorCercleWindowBR", "version_added": "1.0.0", "unique_entry_id": "jDYnxjeL9zxWFsYM3"}, {"name": "green common door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorReliefDR", "version_added": "1.0.0", "unique_entry_id": "3xcS4XeYXbi6A4JJc"}, {"name": "green imperial door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorChineseER", "version_added": "1.0.0", "unique_entry_id": "h59gk2epKc9ALPoF9"}, {"name": "green iron door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronER", "version_added": "1.0.0", "unique_entry_id": "CH2gZGRicug5TB5nF"}, {"name": "green iron grill door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronGrillCR", "version_added": "1.0.0", "unique_entry_id": "fNwKPm8gu5pnoNZ2H"}, {"name": "green metal-accent door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorIronpartsDR", "version_added": "1.0.0", "unique_entry_id": "gveHmLcPh9uNLMFB8"}, {"name": "green rustic door", "image": null, "buy_price": 5000, "category": "Door", "filename": "HouseDoorSimplicityJR", "version_added": "1.0.0", "unique_e
