=== lindsaygelle/AWSAnimalCrossing/src/api_gateway/model/reaction/model.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "filename_icon": {
            "maxLength": 20,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "image": {
            "type": [
                "null"
            ]
        },
        "internal_id": {
            "maxLength": 1114,
            "minLength": 19,
            "type": [
                "number"
            ]
        },
        "name": {
            "maxLength": 18,
            "minLength": 3,
            "type": [
                "string"
            ]
        },
        "unique_entry_id": {
            "maxLength": 17,
            "minLength": 17,
            "type": [
                "string"
            ]
        },
        "version_added": {
            "maxLength": 5,
            "minLength": 5,
            "type": [
                "string"
            ]
        }
    },
    "required": [
        "filename_icon",
        "image",
        "internal_id",
        "name",
        "unique_entry_id",
        "version_added"
    ],
    "title": "Reaction",
    "type": "object"
}

=== lindsaygelle/AWSAnimalCrossing/data/reaction.json
[{"name": "Greetings", "image": null, "version_added": "1.0.0", "filename_icon": "Greeting", "internal_id": 50, "unique_entry_id": "oE6uqhZYjYfuqb55n"}, {"name": "Agreement", "image": null, "version_added": "1.0.0", "filename_icon": "Nodding", "internal_id": 39, "unique_entry_id": "7smqwK9J7eFBxta28"}, {"name": "Disagreement", "image": null, "version_added": "1.0.0", "filename_icon": "Negative", "internal_id": 58, "unique_entry_id": "Bw5YBM6iuWgMzutWq"}, {"name": "Pleased", "image": null, "version_added": "1.0.0", "filename_icon": "Hello", "internal_id": 120, "unique_entry_id": "Z3MuKfQMaH3D8vkPA"}, {"name": "Happiness", "image": null, "version_added": "1.0.0", "filename_icon": "Smiling", "internal_id": 19, "unique_entry_id": "TWENXBbBENgnFiGq3"}, {"name": "Joy", "image": null, "version_added": "1.0.0", "filename_icon": "HappyFlower", "internal_id": 21, "unique_entry_id": "fSNyHJHgLKac5mSLT"}, {"name": "Glee", "image": null, "version_added": "1.0.0", "filename_icon": "HappyDance", "internal_id": 23, "unique_entry_id": "8nAwdhzZfotqpLC9R"}, {"name": "Laughter", "image": null, "version_added": "1.0.0", "filename_icon": "Laughing", "internal_id": 20, "unique_entry_id": "EBenMHMpwnkMgS6eg"}, {"name": "Love", "image": null, "version_added": "1.0.0", "filename_icon": "Love", "internal_id": 22, "unique_entry_id": "GvAsErCFuGAcMAeXM"}, {"name": "Confident", "image": null, "version_added": "1.0.0", "filename_icon": "Assent", "internal_id": 127, "unique_entry_id": "TGifHTbyLBh4f3gDQ"}, {"name": "Showmanship", "image": null, "version_added": "1.0.0", "filename_icon": "Shaki", "internal_id": 62, "unique_entry_id": "Bj5iG7kc6tLND9bjn"}, {"name": "Flourish", "image": null, "version_added": "1.0.0", "filename_icon": "Dance", "internal_id": 60, "unique_entry_id": "5QDD3DcwdPhbGoJAf"}, {"name": "Pride", "image": null, "version_added": "1.0.0", "filename_icon": "SmugFace", "internal_id": 51, "unique_entry_id": "xKoQpdJMtocNFRckm"}, {"name": "Encouraging", "image": null, "version_added": "1.0.0", "filename_icon": "Cheering", "internal_id": 49, "unique_entry_id": "fomfML4NWdY8x6adv"}, {"name": "Delight", "image": null, "version_added": "1.0.0", "filename_icon": "Clapping", "internal_id": 47, "unique_entry_id": "F9DpGeqZzDeSTh2bq"}, {"name": "Apologetic", "image": null, "version_added": "1.0.0", "filename_icon": "Apologize", "internal_id": 126, "unique_entry_id": "jBKsQYCAd7PtymQeB"}, {"name": "Bewilderment", "image": null, "version_added": "1.0.0", "filename_icon": "Pardon", "internal_id": 253, "unique_entry_id": "WRSSRZMtM6rXfXBrR"}, {"name": "Curiosity", "image": null, "version_added": "1.0.0", "filename_icon": "QuestionMark", "internal_id": 41, "unique_entry_id": "SskgipgnKzm5TsK7d"}, {"name": "Surprise", "image": null, "version_added": "1.0.0", "filename_icon": "Aha", "internal_id": 34, "unique_entry_id": "7jmkZiSxrYT7MMm4P"}, {"name": "Amazed", "image": null, "version_added": "1.0.0", "filename_icon": "Shocked", "internal_id": 33, "unique_entry_id": "vosig4bbr4kPq57AT"}, {"name": "Inspiration", "image": null, "version_added": "1.0.0", "filename_icon": "IdeaBulb", "internal_id": 40, "unique_entry_id": "8ux4ddfibJQR2EuWW"}, {"name": "Shocked", "image": null, "version_added": "1.0.0", "filename_icon": "Surprised", "internal_id": 36, "unique_entry_id": "bn29da8SNdMYYyWAa"}, {"name": "Mistaken", "image": null, "version_added": "1.0.0", "filename_icon": "Oops", "internal_id": 59, "unique_entry_id": "DPR7WWkmR36Bsf2LG"}, {"name": "Bashfulness", "image": null, "version_added": "1.0.0", "filename_icon": "Blushing", "internal_id": 44, "unique_entry_id": "wzvKbFrEJCseTohoz"}, {"name": "Shyness", "image": null, "version_added": "1.0.0", "filename_icon": "Hesitate", "internal_id": 57, "unique_entry_id": "9H7jt7AGKbh6mW4y8"}, {"name": "Sheepishness", "image": null, "version_added": "1.0.0", "filename_icon": "WrySmile", "internal_id": 54, "unique_entry_id": "5cRnCPDJRdRpPJF8D"}, {"name": "Smirking", "image": null, "version_added": "1.0.0", "filename_icon": "Grin", "internal_id": 53, "unique_entry_id": "KDAWT9zDKpufEWgaW"}, {"name": "Mischief", "image": null, "version_added": "1.0.0", "filename_icon": "Scheming", "internal_id": 46, "unique_entry_id": "E7it7yLfFaddFvEhQ"}, {"name": "Resignation", "image": null, "version_added": "1.0.0", "filename_icon": "OhGeez", "internal_id": 45, "unique_entry_id": "7YdF3ZMr95XP3FaoW"}, {"name": "Daydreaming", "image": null, "version_added": "1.0.0", "filename_icon": "AbsentMindedness", "internal_id": 61, "unique_entry_id": "JFrTBJCEaX5R4kABT"}, {"name": "Thought", "image": null, "version_added": "1.0.0", "filename_icon": "Thinking", "internal_id": 29, "unique_entry_id": "HEFCeCGtJ7Bkb5PXG"}, {"name": "Sleepy", "image": null, "version_added": "1.0.0", "filename_icon": "Sleepy", "internal_id": 43, "unique_entry_id": "9e5BhxmqtMurNWqW4"}, {"name": "Dozing", "image": null, "version_added": "1.0.0", "filename_icon": "Sleep", "internal_id": 63, "unique_entry_id": "2vvgAacGjthcFW5Qa"}, {"name": "Worry", "image": null, "version_added": "1.0.0", "filename_icon": "Worried", "internal_id": 27, "unique_entry_id": "TygKeKxvotLEzWqvY"}, {"name": "Sighing", "image": null, "version_added": "1.0.0", "filename_icon": "Sighing", "internal_id": 28, "unique_entry_id": "ntjLqg82EQNsgnzYA"}, {"name": "Sadness", "image": null, "version_added": "1.0.0", "filename_icon": "SadSpiral", "internal_id": 30, "unique_entry_id": "Wo8q6KhPtL2CYwat4"}, {"name": "Heartbreak", "image": null, "version_added": "1.0.0", "filename_icon": "BrokenHeart", "internal_id": 42, "unique_entry_id": "ex6gKZu6zsyd6MgDr"}, {"name": "Sorrow", "image": null, "version_added": "1.0.0", "filename_icon": "Crying", "internal_id": 32, "unique_entry_id": "W8nngMS98uwpHHW4m"}, {"name": "Intense", "image": null, "version_added": "1.0.0", "filename_icon": "Silent", "internal_id": 119, "unique_entry_id": "X2kzqTaPwtG6SGNT8"}, {"name": "Aggravation", "image": null, "version_added": "1.0.0", "filename_icon": "Outraged", "internal_id": 25, "unique_entry_id": "6suhKYAAhh5QMKt64"}, {"name": "Cold Chill", "image": null, "version_added": "1.0.0", "filename_icon": "ColdChill", "internal_id": 37, "unique_entry_id": "K62u2owKFDLmPCB3Q"}, {"name": "Distress", "image": null, "version_added": "1.0.0", "filename_icon": "Frantic", "internal_id": 31, "unique_entry_id": "vsSjQBZXPeSK6uDTK"}, {"name": "Fearful", "image": null, "version_added": "1.0.0", "filename_icon": "Shaking", "internal_id": 38, "unique_entry_id": "noKrWYCMSWcH4jwvi"}, {"name": "Sneezing", "image": null, "version_added": "1.0.0", "filename_icon": "Sneezing", "internal_id": 48, "unique_entry_id": "F6Dkk4PGtjDMCgry3"}, {"name": "Haunt", "image": null, "version_added": "1.5.0", "filename_icon": "AddScaring", "internal_id": 801, "unique_entry_id": "fA3nXJsXHNT67zyT2"}, {"name": "Scare", "image": null, "version_added": "1.5.0", "filename_icon": "AddPrank", "internal_id": 805, "unique_entry_id": "sBW2mWEs7FW8mN8e5"}, {"name": "Sit Down", "image": null, "version_added": "1.6.0", "filename_icon": "AddSitDown", "internal_id": 808, "unique_entry_id": "vZLdKXLdnjvN4J5Je"}, {"name": "Wave Goodbye", "image": null, "version_added": "1.6.0", "filename_icon": "AddWaveHands", "internal_id": 809, "unique_entry_id": "dbiQgwwQZxAQw54ur"}, {"name": "Take a Picture", "image": null, "version_added": "1.6.0", "filename_icon": "AddTakePictures", "internal_id": 815, "unique_entry_id": "77uFv5cZp43Rt3LaP"}, {"name": "Sniff Sniff", "image": null, "version_added": "1.6.0", "filename_icon": "AddSmell", "internal_id": 814, "unique_entry_id": "M3JksnoqmWyo9otrd"}, {"name": "Work Out", "image": null, "version_added": "1.6.0", "filename_icon": "AddGymnastics", "internal_id": 804, "unique_entry_id": "oXMGkQsnaXyB2WLKp"}, {"name": "Yoga", "image": null, "version_added": "1.6.0", "filename_icon": "AddYoga", "internal_id": 802, "unique_entry_id": "yeh2FF6fzMn3BdAi6"}, {"name": "Here You Go", "image": null, "version_added": "1.6.0", "filename_icon": "AddHereYouGo", "internal_id": 816, "unique_entry_id": "7mskmgbcDnZMfaa8d"}, {"name": "Excited", "image": null, "version_added": "1.6.0", "filename_icon": "AddExcited", "internal_id": 813, "unique_entry_id": "n7AxvQcyuPEtdD7uF"}, {"name": "Ta-da", "image": null, "version_added": "1.6.0", "filename_icon": "AddPraise", "internal_id": 817, "unique_entry_id": "r5knh2R8vmx7J4pxR"}, {"name": "Confetti", "image": null, "version_added": "1.7.0", "filename_icon": "AddConfetti", "internal_id": 848, "unique_entry_id": "ZQwAqpKEDkTHTQXEn"}, {"name": "Viva", "image": null, "version_added": "1.7.0", "filename_icon": "AddViva", "internal_id": 851, "unique_entry_id": "awBmqTsqEP6vSyH3k"}, {"name": "Let's Go", "image": null, "version_added": "1.7.0", "filename_icon": "AddEntice", "internal_id": 855, "unique_entry_id": "mcdAptLF325uqyDKa"}, {"name": "Feelin' It", "image": null, "version_added": "1.7.0", "filename_icon": "AddDance", "internal_id": 856, "unique_entry_id": "r6wW7uebEBsLwP3XT"}, {"name": "Posture Warm-Up", "image": null, "version_added": "2.0.0", "filename_icon": "AddRadioGymnastics01", "internal_id": 993, "unique_entry_id": "XG5nz2NLapRDsC2Ro"}, {"name": "Arm Circles", "image": null, "version_added": "2.0.0", "filename_icon": "AddRadioGymnastics02", "internal_id": 994, "unique_entry_id": "j4wmMk6NhvHfuM6um"}, {"name": "Side Bends", "image": null, "version_added": "2.0.0", "filename_icon": "AddRadioGymnastics03", "internal_id": 995, "unique_entry_id": "bqJis3YL4LQd6en4T"}, {"name": "Body Twists", "image": null, "version_added": "2.0.0", "filename_icon": "AddRadioGymnastics04", "internal_id": 996, "unique_entry_id": "4gwdwpfJAWceXuEzb"}, {"name": "Wide Arm Stretch", "image": null, "version_added": "2.0.0", "filename_icon": "AddRadioGymnastics05", "internal_id": 997, "unique_entry_id": "NbPWHvrWsEu2CrkgB"}, {"name": "Upper-Body Circles", "image": null, "version_added": "2.0.0", "filename_icon": "AddRadioGymnastics06", "internal_id": 998, "unique_entry_id": "NdqKFNRcviZmKghHD"}, {"name": "Jump", "image": null, "version
